version: '3'
services:
  web:
    build: site
    container_name: mvc-apache
    ports :
     - "80:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
     - database

  database:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mvc-mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mvcphp
      MYSQL_ROOT_PASSWORD: mvcphp_pwd
      MYSQL_USER: mvcphp_user
      MYSQL_PASSWORD: mvcphp_pwd
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mvc-phpmyadmin
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
        - PMA_ARBITRARY=1

volumes:
  db_data:
      
      