/:
  controller: Main
  action: index

/login:
  controller: Main
  action: login

/s-inscrire:
  controller: User
  action: register

/modifier-utilisateur:
  controller: User
  action: edit

/tableau-de-bord:
  controller: Admin
  action: dashboard


/users:
  controller: User
  action: list